# -*- coding: utf-8 -*-
"""Math for ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJv8_A76rXEuj17eSOy434uRmdHrl8SJ

Compute the dot product of vectors 𝑎=[1,2,3] and b=[4,5,6]. Extend this by implementing a function to compute dot products for higher dimensions.
"""

def dotProduct(vectors):
  size = len(vectors[0])
  for j in vectors:
    if len(j)!=size:
      raise ValueError("Unequal Size")
  val = 0
  for i in range(size):
    temp = 1
    for vect in vectors:
      temp *= vect[i]
    val +=temp

  return val

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
vector3 = [7, 8, 9]
dotProduct([vector1,vector2,vector3])

"""Perform matrix multiplication with
𝐴
=
[
1
2
3
4
] and
𝐵
=
[
5
6
7
8
]
. Extend to multiply large sparse matrices.
"""

def matrixMult(a,b):
  m1_row = len(a)
  m1_col = len(a[0])
  m2_col = len(b[0])

  new_matrx = [[ 0 for _ in range(m2_col)] for _ in range(m1_row) ]
  print(new_matrx)
  for i in range(m1_row):
    for j in range(m2_col):
      for g in range(m1_col):
        new_matrx[i][j] += a[i][g]*b[g][j]
  print(new_matrx)



a = [[2,5,6]]
b= [[3],[4],[-5]]
matrixMult(a,b)