# -*- coding: utf-8 -*-
"""Math for ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJv8_A76rXEuj17eSOy434uRmdHrl8SJ

Compute the dot product of vectors 𝑎=[1,2,3] and b=[4,5,6]. Extend this by implementing a function to compute dot products for higher dimensions.
"""

def dotProduct(vectors):
  size = len(vectors[0])
  for j in vectors:
    if len(j)!=size:
      raise ValueError("Size unqual")
  val = 0
  for i in range(size):
    temp = 1
    for vect in vectors:
      temp *= vect[i]
    val +=temp

  return val

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
vector3 = [7, 8, 9]
dotProduct([vector1,vector2,vector3])

"""Perform matrix multiplication with
𝐴
=
[
1
2
3
4
]
A=[
1
3
​
  
2
4
​
 ] and
𝐵
=
[
5
6
7
8
]
B=[
5
7
​
  
6
8
​
 ]. Extend to multiply large sparse matrices.
"""

