# -*- coding: utf-8 -*-
"""Numpy and Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVroTZ3MjfYIbWAyLY9eiPpm5rPPa8u0

# Week 2: Python for Data Science

**NumPy Exercises:**
"""

import numpy as np
from numpy import random

"""1. Create a 3x3 NumPy array of random numbers and compute its transpose. Extend by performing matrix factorization (LU decomposition).

"""

array1 = random.randint(100,size = (3,3))
print(array1)
print("transpose")
array2 = np.transpose(array1)
print(array2)

"""2. Perform element-wise multiplication of arrays
𝑎
=
[
1
2
3
]
 and
𝑏
=
[
4
5
6
]
]. Extend to implement and use broadcasting.
"""



"""**pandas Exercises**

1. Load the Titanic dataset from a CSV file into a pandas DataFrame. Extend to perform advanced data cleaning and transformation tasks.
"""



"""2. Handle missing values in the Age column by filling with the median age. Extend to perform imputation using k-Nearest Neighbors."""



"""3. Group the data by the 'Pclass' column and compute the average age for each class. Extend to perform multi-level grouping and aggregations."""

