# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxhSnD87RCSUCxpFxHC3GX-efXBHcnfG

# Week 3: Data Visualization and Exploratory Data Analysis

Data Visualization **Exercises**
"""

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/content/Titanic-Dataset.csv")

"""1. Create a histogram of passenger ages using the Titanic dataset. Extend to create interactive plots using Plotly."""

plt.figure()
df[["Age"]].plot.hist(alpha=0.5)

import plotly.express as px
fig = px.histogram(df, x="Age")
fig.show()

"""2. Plot a scatter plot showing the relationship between Age and Fare. Extend to create 3D scatter plots and analyze clusters."""

df.plot.scatter("Age","Fare",s=50)

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(df[["Age"]], df[["Fare"]], marker = 2)
plt.show()



"""3. Use seaborn to create a heatmap of the correlation matrix of numerical features. Extend to use seaborn for complex categorical plot types."""

